### ISSUE TITLE
Clean code and don't repeat yourself 

### ISSUE THREAD

**Issue by bnazmi** [FACG5/flawless-todo-list#20]
you use select element by getElementById and repeat it much time! that's not good try to create a function and just pass the class or id to do this work!
`function select(selectors) {
     return document.querySelector(selectors);
}`

**Comment by MohammedYehia** [comment]
as @bnazmi  said used something like the one in the traffic light challenge
https://github.com/foundersandcoders/morning-challenge-traffic-lights/blob/6cf2b0b78d45572b79e2a9650944cec2377354c6/script.js#L29
