### ISSUE TITLE
i think should put this on body selector

### ISSUE THREAD

**Issue by bnazmi** [FACG5/flawless-todo-list#21]
https://github.com/FACG5/flawless-todo-list/blob/4be0ab4ef282be1ef7806db071a34ff462cb8529/style.css#L1-L3

the * selector use to selects all elements and can use it to prefix the padding and margin to page 
when u need to set font u can use the body selectors

**Comment by ali-7** [comment]
if i want the font size and family to be applied to the whole page wouldn't be better to put it to the general selector and not only in the body ?
