### ISSUE TITLE
A better sort function

### ISSUE THREAD

**Issue by NoureldeanSaed** [FACG5/flawless-todo-list#24]
https://github.com/FACG5/flawless-todo-list/blob/4be0ab4ef282be1ef7806db071a34ff462cb8529/logic.js#L55

You can instead of 3 for loops do this...
```javascript
sortTodos: function(todos) {
  var clone = todoFunctions.cloneArrayOfObjects(todos);
  return clone.sort(function(a,b) {
    if ((a.priority === 'high' && b.priority === 'medium') || (a.priority === 'medium' && b.priority === 'low')) return 1;
    else ((a.priority === 'medium' && b.priority === 'high') || (a.priority === 'low' && b.priority === 'medium')) return -1;
    else return 0;
}
```

**Comment by HemaSAli** [comment]
thanks nour ,  I really looked for sort by using sort 
I will replace my function with your function

**Comment by NoureldeanSaed** [comment]
@hemaSAli my function is no where near perfect, I was just saying you don't need to use 3 loops to sort your array, you could always do better than I did :) .

**Comment by HemaSAli** [comment]
@NoureldeanSaed thanks  , I will try to do it .
