### ISSUE TITLE
map,filter,concat are pure function 

### ISSUE THREAD

**Issue by MohammedYehia** [FACG5/flawless-todo-list#25]
https://github.com/FACG5/flawless-todo-list/blob/4be0ab4ef282be1ef7806db071a34ff462cb8529/logic.js#L26-L27

you don't need to use cloneArrayObject unless you used forEach or the normal loop that affect the original array

**Comment by IsraaMoqbel** [comment]
OOps sorry I told you @HemaSAli to use the clone function I didn't see that you are using the concat!
